---
- name: Create Consul service definition
  include_role: name=consul-service
  vars:
    consul_config_name: 'grafana'
    consul_services:
      - name: 'grafana'
        tags: ['monitor', 'metrics-view']
        port: '{{ grafana_port }}'
        checks:
          - id: grafana-health
            name: Grafana current health
            type: http
            http: 'http://localhost:{{ grafana_port }}/api/health'
