---
- name: Create compose file
  template:
    src: 'docker-compose.yml.j2'
    dest: '{{ grafana_compose_file }}'
    owner: 'dockremap'
    group: 'docker'
    mode: 0640

- name: Create containers
  docker_compose:
    project_src: '{{ grafana_service_path }}'
    pull: true
    build: false
    state: '{{ compose_state }}'
    restarted: '{{ compose_restart }}'
    recreate: '{{ grafana_config.changed | ternary("always", compose_recreate) }}'
