---
- name: Create compose file
  template:
    src: 'docker-compose.yml.j2'
    dest: '{{ grafana_compose_file }}'
    owner: 'dockremap'
    group: 'docker'
    mode: 0640

- name: Create containers
  community.docker.docker_compose_v2:
    project_src: '{{ grafana_service_path }}'
    pull:        '{{ compose_pull }}'
    state:       '{{ compose_state }}'
    recreate:    '{{ grafana_config.changed | ternary("always", compose_recreate) }}'
