---
# Necessary to hide a few sensitive paths
- name: Configure Nginx proxy
  include_role: name=infra-role-nginx
  vars:
    nginx_sites:
      '{ "{{ grafana_domain }}": {{ grafana_ssl_default_backend }} }'
